jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      # - checkout
      - run: echo "A first hello hi"
      # - run: mkdir -p my_workspace
      # - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run: cd 
      - run: mkdir testdir
      - run: cd testdir
      - run: pwd
      - persist_to_workspace:
          root: ~/testdir
          paths:
            - "*"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      # - checkout
      - run: echo "Circile CI Test starting..."
      - run: cd testdir
      - run: ./runTest.sh
      - store_test_results:
          path: /tmp/test-results
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
