version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: dir
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: dir


workflows:
  version: 2
  build_and_test:
    jobs:
      - build1:
          context: MyContext # has an env var called MY_ENV_VAR
      - test:
          requires:
            - build1
   

