jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      # - checkout
      - run: echo "A first hello hi"
      # - run: mkdir -p my_workspace
      # - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run:
          name: Creating new Diroectory
          command: |
            pwd
            cd
            mkdir testdir
            cd testdir
            pwd
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      # - checkout
      - run: echo "Circile CI Test starting..."
      - run: pwd
      - run:
          name: Checking Folders
          command: |
            pwd
            cd
            cd testdir
            pwd
      # - run: cd testdir
      - run: ./runTest.sh
      - store_test_results:
          path: /tmp/test-results
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
