version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build1:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: dir
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: dir

  build2: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'


workflows:
  version: 2
  build_and_test:
    jobs:
      - build1:
          context: MyContext # has an env var called MY_ENV_VAR
      - test1:
          requires:
            - build1
      - build2:
   

