version: 2.1
jobs: 
  build:
    docker:
      - image: ubuntu:bionic
        environment:
          PYAPS_HOME: /root/tools/PyAPS
          CONDA_PREFIX: /root/tools/miniconda3
          MINTPY_HOME: /root/tools/MintPy
        user: root

    steps:
      - checkout
      - run:
          name: Setting Environment with Miniconda
          command: |
            ls
       
workflows: 
  version: 2
  build_and_test:
    jobs:
      - build
