jobs:
  build:
    docker: 
      - image: circleci/ruby:2.4.1
    steps:
      # - checkout
      - run: echo "A first hello hi"
      # -  run: mkdir -p my_workspace
      # - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run:
          name: Creating new Diroectory
          command: |
            pwd
            mkdir testdir1
            cd testdir1
            pwd
            mkdir testdir2
            cd testdir2
            pwd
            echo "EnvVarTest"
            echo $MY_ENV_VAR
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Creating new Diroectory
          command: |
            echo "EnvVarTest"
            echo $MY_ENV_VAR

      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: MyContext # has an env var called MY_ENV_VAR
      - test:
          requires:
            - build
