version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: dir
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: dir
   
  test_win_conda: # name of your job
    executor: win/default # executor type
    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - run:
          name: Setting Environment Variables
          shell: cmd.exe
          command: |
            set ENV_VAR=value
            echo %ENV_VAR%
            set NEW_ENV_VAR=%ENV_VAR%/testdir
            echo %NEW_ENV_VAR%
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build1:
          context: MyContext # has an env var called MY_ENV_VAR
      - test:
          requires:
            - build1
      - test_win_conda:
          requires:
            - build1        

