jobs:
  build:
    docker:
      - image: dockermiami/debianimage:latest
        user: root
    steps:
      - run:
          name: Setting Environment Variables
          command: |
            pwd
            ls
            echo "END"
      
      - persist_to_workspace:
          root: /root
          paths:
            - tools
            
  test_linux_conda:
    docker:
      - image: dockermiami/debianimage:latest
        user: root
    steps:
      - run:
          name: Installing Dependencies via Conda
          command: |
            pwd
            ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_linux_conda:
          requires:
            - build
