version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
        user: root
    steps:
      - checkout
      - run:
          name: Install MintPy
          command: |
            ./install.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
