jobs:
  build:
    docker:
      - image: dockermiami/debianimage:latest
        user: root
    steps:
      - run:
          name: Setting Environment Variables
          command: |
            pwd
            ls
            cd /home
            ls
            echo "END"
      - run:
          name: Build docker image
          command: |
            mkdir images
            SHA1=$(echo $CIRCLE_SHA1 | cut -c1-7)
            echo "export TAG=$SHA1" >> images/env.sh
            source images/env.sh
            docker build --rm --force-rm -t dockermiami/debianimage:$TAG -f docker/Dockerfile .
            cd images
            docker save dockermiami/debianimage:$TAG > isce2.tar
      - persist_to_workspace:
          root: images
          paths:
            - "*"

  test_linux_conda:
    docker:
      - image: dockermiami/debianimage:latest
        user: root
    steps:
      - setup_remote_docker
      - run:
          name: Installing Dependencies via Conda
          command: |
            pwd
            ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_linux_conda:
          requires:
            - build
