version: 2.1
jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps:
      - checkout
      - run:
          name: Install MintPy
          command: |
            ./install.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
