jobs:
  build:
    docker:
      - image: ubuntu:bionic
        user: root
    steps:
      - run:
          name: Setting Environment Variables
          command: |
            pwd
            ls
            cd /home
            ls
            echo $MY_ENV_VAR
            mkdir $MY_ENV_VAR
            cd $MY_ENV_VAR
            pwd
            echo "END"
      
  test_linux_conda:
    docker:
      - image: dockermiami/debianimage:latest
        user: root
    steps:
      - run:
          name: Installing Dependencies via Conda
          command: |
            pwd
            ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_linux_conda:
          requires:
            - build
