jobs:
  build:
    docker:
      - image: ubuntu:bionic
        user: root
    environment:
      - MINTPY_HOME: ~/tools/MintPy 
    steps:
      - run:
          name: Setting Environment Variables
          command: |
            pwd
            echo ${MINTPY_HOME}
            echo "1"
            export PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}
            export PATH=${PATH}:${MINTPY_HOME}/mintpy
            export PYAPS_HOME=~/tools/PyAPS
            export PYTHONPATH=${PYTHONPATH}:${PYAPS_HOME}
            echo "PythonPath"
            echo ${PYTHONPATH}
            echo "Path"
            echo ${PATH}
            echo "PaAps_Home"
            echo ${PYAPS_HOME}
            echo "END"
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

