jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
            MY_ENV_VAR_1: test_env_var
            MY_ENV_VAR_2: my-value-2
    steps:
      # - checkout
      - run: echo "A first hello hi"
      # - run: mkdir -p my_workspace
      # - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run:
          name: Creating new Diroectory
          command: |
            pwd
            mkdir testdir1
            cd testdir1
            pwd
            mkdir testdir2
            cd testdir2
            pwd
            echo "EnvVarTest"
            echo $MY_ENV_VAR_1
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - testdir1
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: /home/circleci/project
      # - checkout
      - run: echo "Circile CI Test starting..."
      - run: pwd
      - run:
          name: Checking Folders
          command: |
            pwd
            ls
            cd testdir1
            pwd
            ls
            echo "EnvVarTest"
            Echo $MY_ENV_VAR_1
      # - run: cd testdir
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
