version: 2.1

jobs:
  build:
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:

