version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/python:3.6.4 
        environment:
          PYAPS_HOME: /root/tools/PyAPS
          CONDA_PREFIX: /root/tools/miniconda3
          MINTPY_HOME: /root/tools/MintPy
          CIRCLE_WORKING_DIRECTORY: ~/project/meissam
          
        user: root
    working_directory: ~/project/meissam
    steps:
      - run:
          name: Setting Environment with Miniconda
          command: |
            apt update
            apt-get update --yes && apt-get upgrade --yes
            apt-get install --yes git wget
      - run:
          name: DIR
          command: |
            ls
            
      - checkout
      - run:
          name: Setting Environment with Miniconda
          command: |
            ls
            pwd
            echo $CIRCLE_WORKING_DIRECTORY
            python --version
            ./runTest.sh
            

       
workflows: 
  version: 2
  build_and_test:
    jobs:
      - build
